- name: deb2
  debug:
    msg: "{{ file }}"
- name: copy file
  template:
    src: "{{ FABSIBLE_CWD|default('..')+'/files/apps/'+file.value.src }}"
    dest: "{{ file.value.dest }}"
  notify: "{{ notifiers|default([]) }}"
